name: Build Windows

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: choco install php nsis --yes

      - name: Configure
        shell: bash
        run: |
          mkdir build && cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 \
            -DCMAKE_BUILD_TYPE=Release -DBUILD_SWS_PYTHON=NO

      - name: Build
        run: cmake --build build --config Release

      - name: Create installer
        run: cd build && cpack -G NSIS -C Release

      - name: Upload plugin
        uses: actions/upload-artifact@v4
        with:
          name: reaper_sws-x86_64-windows
          path: build/reaper_sws*.dll

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: reaper_sws-x86_64-windows-installer
          path: build/sws-*.exe
